# Classical Mechanics I (PHYS 311)
## Studio 13

*Name:* Connor Haskell

*Date:* 12/2/2024

## Matrix Operations

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Google how to represent matrices in numpy. If any of the following bolded terms are unfamiliar to you, google them! Wikipedia is your friend.

* Create a 3x3 matrix A.
* Demonstrate how to multiply that matrix by a scalar.
* Demonstrate multiplying A by a different 3x3 matrix. (This is not with the `*` operator!)
* Multiply A by a (3D) vector. (i.e. calculate Av)
* Calculate the **transpose** of A.
* Calculate the **trace** of A.
* Calculate the **determinant** of A.
* Calculate the **inverse** of A if it exists.
* Create a 3-vector with nonzero x,y,z components, and rotate it about the x axis by an angle $pi/2$. Look up the form of a 3D rotation matrix.
* EC(+0.5): Demonstrate a nonzero rotation of a 10-dimensional vector $\vec{v}=(x_1,x_2,...,x_10)$ in the $x_1,x_2$ plane

Google how to find the eigenvectors of matrices in numpy.

* Calculate a moment of inertia tensor for a system of two particles with equal mass (let's set it to 1). One at the origin, and the other at (1,1,0). 
* Find the eigenvectors of this new moment of inertia tensor. (Comment on the resulting eigenvectors!) Notice that numpy will return normalized eigenvectors.
* EC(+0.5): Now that you have the eigenvectors, you can express your system in a coordinate system defined by these three eigenvectors. Calculate the the second particle position in this new coordinate system. (Remember that the $x^\prime$ component of a vector $\vec{v}$ will just be $\vec{v}\cdot\hat{x}^{\prime}$.) You should have new descriptions of the two particle positions in this new basis. Calculate the moment of inertia tensor in this new coordinate system and show that it's diagonal! i.e. the Eigenvectors of the matrix are the principle axes!

In [2]:
matrixA = array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix A:")
print(matrixA)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
Scalar_mult = 2*matrixA
print("Matrix A multiplied by Scalar (2):")
print(Scalar_mult)

Matrix A multiplied by Scalar (2):
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [4]:
matrixB = array([[9,8,7],[6,5,4],[3,2,1]])
matrixBdotA = matrixA@matrixB
print("Matrix A dot Matrix B:")
print(matrixBdotA)

Matrix A dot Matrix B:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [5]:
vectorA = array([1,2,3])
matrixAdot_vectorA = matrixA @ vectorA
print("Matrix A dot Vector A:", matrixAdot_vectorA)


Matrix A dot Vector A: [14 32 50]


In [6]:
matrixA_trans = matrixA.T
print("Transpose of Matrix A:\n", matrixA_trans)

Transpose of Matrix A:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [7]:
matrixA_trace = trace(matrixA)
print("Trace of Matrix A:", matrixA_trace)


Trace of Matrix A: 15


In [8]:
matrixA_det = linalg.det(matrixA)
print("Determinant of Matrix A:", matrixA_det)

Determinant of Matrix A: -9.51619735392994e-16


In [9]:
threshold = 1e-10


matrixA_det = linalg.det(matrixA)


if abs(matrixA_det) > threshold:
    matrixA_inv = linalg.inv(matrixA)
    print("Inverse exists. Inverse of Matrix A is:", matrixA_inv)
else:
    print("Inverse does not exist because the determinant is below the threshold.")

Inverse does not exist because the determinant is below the threshold.


In [10]:
theta = pi / 2

rotation_matrix = np.array([[1, 0, 0],[0, np.cos(theta), -np.sin(theta)],[0, np.sin(theta), np.cos(theta)]])
vectorA_rotated = rotation_matrix @ vectorA

print("Original VectorA:", vectorA)
print("Rotated VectorA:", vectorA_rotated)

Original VectorA: [1 2 3]
Rotated VectorA: [ 1. -3.  2.]


In [11]:
v = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

theta = np.pi / 6 


rotation_matrix = eye(10)

#creates a 10x10 identity matrix
#then use the 3D rotation for x1 x2 plane

rotation_matrix[1, 1] = cos(theta)
rotation_matrix[1, 2] = sin(theta)
rotation_matrix[2, 1] = sin(theta)
rotation_matrix[2, 2] = cos(theta)

rotated_vector = rotation_matrix @ v

print("Original Vector:", v)
print("Rotated Vector:", rotated_vector)

Original Vector: [ 1  2  3  4  5  6  7  8  9 10]
Rotated Vector: [ 1.          3.23205081  3.59807621  4.          5.          6.
  7.          8.          9.         10.        ]


In [12]:
# xyz components for the position vectors of different masses m0 and m1

x0 = 0
y0 = 0
z0 = 0
x1 = 1
y1 = 1
z1 = 0
m = 1


Ixx = m*(y0**2 + z0**2) + m*(y1**2 + z1**2)
Iyy = m*(x0**2 + z0**2) + m*(x1**2 + z1**2)
Izz = m*(y0**2 + x0**2) + m*(y1**2 + x1**2)
Ixy = Iyx = -m*(x0*y0) -m*(x1*y1)
Ixz = Izx = -m*(x0*z0) -m*(x1*z1)
Izy = Iyz = -m*(z0*y0) -m*(z1*y1)

MoI_tensor = array([
    [Ixx, Ixy, Ixz],
    [Iyx, Iyy, Iyz],
    [Izx, Izy, Izz]
])

print("Moment of Inertia Tensor is:")
print(MoI_tensor)

Moment of Inertia Tensor is:
[[ 1 -1  0]
 [-1  1  0]
 [ 0  0  2]]


In [13]:
eigenvalues, eigenvectors = linalg.eig(MoI_tensor)


print("Eigenvalues are:")
print(eigenvalues)
print("\nEigenvectors are:")
print(eigenvectors)

Eigenvalues are:
[2. 0. 2.]

Eigenvectors are:
[[ 0.70710678  0.70710678  0.        ]
 [-0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
